
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: admin


development:
  <<: *default
  database: wallet_manager_development

test:
  <<: *default
  database: wallet_manager_test

production:
  <<: *default
  # database: wallet_manager_production
  url: <%= ENV['DATABASE_URL'] %>

